# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
ZSH_THEME="terminalparty"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to  shown in the command execution time stamp
# in the history command output. The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|
# yyyy-mm-dd
HIST_STAMPS="yyyy-mm-dd"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git vi-mode history debian)

source $ZSH/oh-my-zsh.sh

####################
# User configuration
####################

# History settings
HISTSIZE=1000
SAVEHIST=2000
setopt appendhistory

# don't beep
unsetopt beep

# Additional functions
source $HOME/.shell-functions

# PATH settings
source $HOME/.shell-path

# Aliases
source $HOME/.shell-aliases

# Environment variables
source $HOME/.shell-env

