#!/bin/bash

# run dbus - not needed as for now
eval `dbus-launch --auto-syntax`

setxkbmap pl
# Remap keys
xmodmap .Xmodmap

# Load resources
xrdb -merge .Xresources

# turn off that annoying beep
xset b off
# key delay and repeat rate
xset r rate 500 40

# Set the background color
feh --bg-scale /home/mateusz/img/wallpaper

is_executable () {
    [[ ! -z  `command -v $1` ]] && return 0 || return 1
}

# start pulseaudio
if ( is_executable start-pulseaudio-x11 ); then
    start-pulseaudio-x11 &
fi

## Fire up apps
# xcompmgr
if ( is_executable xcompmgr ); then
    xcompmgr -n -r 0 &
fi

# mpd
MPD_RUNNING=`ps -e | grep mpd`
if [ -x /usr/bin/mpd -a -z "$MPD_RUNNING" ] ; then
    mpd
fi

# xscreensaver
if ( is_executable xscreensaver ); then
    xscreensaver -no-splash &
fi

# urxvt daemon
urxvtd -q -o -f

# network manager
if ( is_executable nm-applet ); then
   nm-applet --sm-disable &
fi

# sound applet
if ( is_executable gnome-sound-applet); then
    gnome-sound-applet &
fi

# redshift - Kraków coordinates
if ( is_executable gtk-redshift ); then
    gtk-redshift -l 50.0614:19.9372 &
fi

# dropbox
if ( is_executable dropbox ); then
    dropbox start &
fi

# thunar, file manager; automounting
if ( is_executable thunar ); then
    thunar --daemon &
fi

# ibus daemon - for japanese input
if ( is_executable ibus-daemon ); then
    ibus-daemon --xim -r &
fi

# run xmonad
exec ~/.cabal/bin/xmonad

