#!/bin/bash
# vim: ft=sh

# load basic functions library
source ~/.shell-functions

PROGRAM_NAME=$(basename $0)

print_install_message () {
cat << EOF
Using this script requires eCryptfs to be installed and set up.

    sudo apt-get install ecryptfs-utils
    $PROGRAM_NAME setup

EOF
}

install_symlink () {
    local from=$1
    local to=$2

    if [[ -d $HOME/$to ]]; then
        echo "WARNING: ~/$to already exists, will not symlink."
    else
        ln -s $HOME/private/$from $HOME/$to
    fi
}

setup_ecrypt () {
    if (is_not_executable ecryptfs-setup-private); then
        print_install_message
        exit 1
    fi

    ecryptfs-setup-private --noautomount
    sed -i 's/Private/private/g' $HOME/.ecryptfs/Private.mnt

    mkdir -p $HOME/.config

    install_symlink purple .purple
    install_symlink filezilla .config/filezilla
}

mount_ecrypt () {
    if (is_not_executable ecryptfs-mount-private); then
        print_install_message
        exit 1
    fi

    ecryptfs-mount-private
}

umount_ecrypt () {
    if (is_not_executable ecryptfs-umount-private); then
        print_install_message
        exit 1
    fi

    ecryptfs-umount-private
}

case $1 in
    mount)
        mount_ecrypt
        ;;

    umount)
        umount_ecrypt
        ;;

    setup)
        setup_ecrypt
        ;;

    *)
        echo "Usage $PROGRAM_NAME (setup|mount|umount)"
esac

